### ISSUE TITLE
UHC and ESOC Patch for AOE3 TAD

### ISSUE THREAD

**Issue by hxazgalor** [danielpereira/AoE3UnHardcoded#2]
Apologies for this, but I was hoping to get some help on this matter.

I recently downloaded and installed the **ESO Community Patch** from their website, and was hoping to use the UHC patch in tandem with the ESOC one. I'm told that both can be used together without a hitch. When I selected the ESOC patch's executable (agef.exe) to be patched, I naturally get the message that it's not a "valid AoE3 TAD executable", but I proceed with it. Once I load the game and try to set up a Skirmish match after pressing Play, the game immediately crashes back to the desktop with the generic "X has has encountered an error" message.

Am I doing this correctly, or am I missing a crucial step or two to get it to work?

Would like your thoughts/advice on this. Thanks!

**Comment by danielpereira** [comment]
Hello!

Unfortunately, the latest version of the UHC patch is not totally compatible with the ESOC Patch.

Sorry for the trouble :/

Best regards,
Daniel Pereira
