### ISSUE TITLE
Custom native civs crash

### ISSUE THREAD

**Issue by ekudryavcev** [danielpereira/AoE3UnHardcoded#9]
Adding a native civ through the UHC config file leads to immediate crashes when trying to age up. Even if implemented correctly in the politiciandata.XML and techtreey.XML, the council-style age up does not work for the custom civ.
Other native civ features work flawlessly.

**Comment by danielpereira** [comment]
Hey there!

Sorry for taking way too long to answer, I have been quite busy lately. 

Are you sure you have set the "nativeciv" parameter in the new politiciandata entries correctly? When implementing new Native civs through UHC, it needs to be set to the name of the civ you are adding. Besides of that, do all of the new politician technologies and politiciandata entries have unique names?

(PS: It's worth to mention that, even if two or more civs are supposed to use the same council politician with the same effects, two separate techs and two separate politiciandata entries with different names need to be created)

Best regards,
Daniel Pereira

**Comment by ekudryavcev** [comment]
Thanks for answering!I copied the format from other native civs with unique names, so I suppose politiciandata should be correct. I'll check again in a moment. If you would like, I can send you the XML file. By the way, I've run some tests, like "breaking" the original native civs politicians. Never the behavior of the game was crashing in such cases. For example, if I do not properly state the civ name in the politiciandata, the age up screen will show five blank unavailable politicians, but no crashes. If I misspell a politician name, the tech will be unavailable as though used before, but, again, nothing worse than that. All this seems like the game does not treat the new civ like a proper native civ, and that leads to a crash.
Kind regards,
Jeremy

**Comment by danielpereira** [comment]
Hey again.

I decided to run some tests on my own, and, well, the code that handles Native Civ features regarding Age-Up indeed seems to be buggy... I'll try to see if I can get that fixed and release a new patch today.

Thanks for reporting this bug and bringing my attention to this critical issue!

Best regards,
Daniel Pereira

**Comment by ekudryavcev** [comment]
Glad to hear you'll help! Thank you for your amazing work.

**Comment by danielpereira** [comment]
I just released v1.10. This should fix that issues and a bunch of other issues which were fixed in the code, but not in the official release. Once again, thanks a lot for the help :)

Best regards,
Daniel Pereira

**Comment by ekudryavcev** [comment]
Thank you for dealing with the problem so fast! You're a true gift to the community. 
Best of luck,
Jeremy
